---

# Available Jinja2 variables:
# ---------------------------
# * {{ php_all_versions }}:  Array of all PHP versions


all:
  type: pecl

7.4:
  type: pecl
  version: 3.1.6

7.3:
  type: pecl
  version: 3.1.6

7.2:
  type: pecl
  version: 3.1.6

7.1:
  type: pecl
  version: 2.9.8

7.0:
  type: pecl
  version: 2.9.0

5.6:
  type: pecl
  version: 2.4.1

5.5:
  type: pecl
  version: 2.4.1

5.4:
  type: pecl
  version: 2.4.1

5.3:
  type: pecl
  version: 2.2.7

5.2:
  type: pecl
  version: 2.2.7
