---

# Available Jinja2 variables:
# ---------------------------
# * {{ php_all_versions }}:  Array of all PHP versions


all:
  type: git
  git_url: https://github.com/phalcon/cphalcon
  git_ref: |
    $(git for-each-ref --format='%(*creatordate:raw)%(creatordate:raw) %(refname)' refs/tags \
      | sort -V \
      | sed 's/^.*tags\///g' \
      | grep -E '^v[.0-9]+$' \
      | tail -1 \
    ) \
  command: cd build && ./install
  build_dep: [libpcre-dev, re2c]
  run_dep: []

7.3:
  type: git
  git_url: https://github.com/phalcon/cphalcon
  git_ref: v4.1.2
  command: cd build && ./install

7.2:
  type: git
  git_url: https://github.com/phalcon/cphalcon
  git_ref: v4.1.1
  command: cd build && ./install

7.1:
  type: git
  git_url: https://github.com/phalcon/cphalcon
  git_ref: v3.4.4
  command: cd build && ./install

7.0:
  type: git
  git_url: https://github.com/phalcon/cphalcon
  git_ref: v3.4.4
  command: cd build && ./install

5.6:
  type: git
  git_url: https://github.com/phalcon/cphalcon
  git_ref: v3.4.4
  command: cd build && ./install

5.5:
  type: git
  git_url: https://github.com/phalcon/cphalcon
  git_ref: v3.4.4
  command: cd build && ./install

5.4:
  type: git
  git_url: https://github.com/phalcon/cphalcon
  git_ref: phalcon-v2.0.13
  command: cd build && ./install

5.3:
  type: git
  git_url: https://github.com/phalcon/cphalcon
  git_ref: phalcon-v2.0.9
  command: cd build && ./install
