---

# Available Jinja2 variables:
# ---------------------------
# * {{ php_all_versions }}:  Array of all PHP versions


all:
  type: pecl
  build_dep: [zlib1g-dev]

7.4:
  type: pecl
  version: 4.0.5.2

7.3:
  type: pecl
  version: 4.0.5.2

7.2:
  type: pecl
  version: 4.0.5.2

7.1:
  type: pecl
  version: 4.0.5.2

7.0:
  type: pecl
  version: 4.0.5.2

5.6:
  type: pecl
  version: 2.2.7

5.5:
  type: pecl
  version: 2.2.7

5.4:
  type: pecl
  version: 2.2.7

5.3:
  type: pecl
  version: 2.2.7

5.2:
  type: pecl
  version: 2.2.7
