---

# Available Jinja2 variables:
# ---------------------------
# * {{ php_all_versions }}:  Array of all PHP versions


all:
  type: pecl
  command: printf "\n\n\nyes\nyes\nyes\n" | pecl install memcached
  build_dep: [zlib1g-dev, libmemcached-dev, libevent-dev]
  run_dep: [libmemcachedutil2, libevent-2.1-7]

8.2:
  type: git
  git_url: https://github.com/php-memcached-dev/php-memcached
  git_ref: master
  command: |
    true \
    # FIXME: This is a work-around to mitigate compile error with PHP 8.2
    && sed -i'' 's/\sTSRMLS_CC//g' php_memcached_session.c \
    && phpize \
    && ./configure --enable-memcached \
    && make -j$(getconf _NPROCESSORS_ONLN) \
    && make install \

7.2:
  type: pecl
  command: printf "\n\n\nyes\nyes\nyes\n" | pecl install memcached
  run_dep: [libmemcachedutil2, libevent-2.1-6]

7.1:
  type: pecl
  command: printf "\n\n\nyes\nyes\nyes\n" | pecl install memcached
  run_dep: [libmemcachedutil2, libevent-2.1-6]

7.0:
  type: pecl
  command: printf "\n\n\nyes\nyes\nyes\n" | pecl install memcached
  run_dep: [libmemcachedutil2, libevent-2.0-5]

5.6:
  type: pecl
  version: 2.2.0
  run_dep: [libmemcachedutil2, libevent-2.0-5]

5.5:
  type: pecl
  version: 2.2.0
  run_dep: [libmemcachedutil2, libevent-2.0-5]

5.4:
  type: pecl
  version: 2.2.0
  run_dep: [libmemcachedutil2, libevent-2.0-5]

5.3:
  type: pecl
  version: 2.2.0
  run_dep: [libmemcachedutil2, libevent-2.0-5]

5.2:
  type: pecl
  version: 2.1.0
  run_dep: [libmemcachedutil2, libevent-2.0-5]
